### ISSUE TITLE
single leaf doesn't add a paired leaf

### ISSUE THREAD

**Issue by JohnSmall** [openblockchains/merkletree.rb#1]
Just playing around with this.

I noticed that if I add a single hash, that hash become the Merkle root. I thought that a Merkle tree was supposed to add a duplicate for any unpaired leafs. So if I add one leaf node, I expect the Merkle root to be the hash of two copies of the leaf node.

I've forked the repo. Will sort it out and send you a PR.

**Comment by geraldb** [comment]
Good point. I'd say no. If you have just one hash you do NOT need a hash tree.  Not a merkle tree expert but before you send a PR can you please check some other merkl tree (libraries) and how they handle the one single hash. Cheers. Prost. Greetings from Vienna. Thanks for playing around with merkletree.rb.
